
from _cffi_backend import FFI
from typing import TypeAlias

INVALID_DEVID: int

AES_ENABLED: int
AES_SIV_ENABLED: int
AESGCM_STREAM_ENABLED: int
ASN_ENABLED: int
CHACHA_ENABLED: int
CHACHA_STREAM_ENABLED: int
CHACHA20_POLY1305_ENABLED: int
DES3_ENABLED: int
ECC_ENABLED: int
ED25519_ENABLED: int
ED448_ENABLED: int
ERROR_STRINGS_ENABLED: int
FIPS_ENABLED: int
HMAC_ENABLED: int
KEYGEN_ENABLED: int
HKDF_ENABLED: int
ML_DSA_ENABLED: int
ML_KEM_ENABLED: int
MPAPI_ENABLED: int
PWDBASED_ENABLED: int
RSA_ENABLED: int
RSA_PSS_ENABLED: int
SHA_ENABLED: int
SHA3_ENABLED: int
SHA256_ENABLED: int
SHA384_ENABLED: int
SHA512_ENABLED: int
WC_RNG_SEED_CB_ENABLED: int

FIPS_VERSION: int

WC_MGF1NONE: int
WC_MGF1SHA1: int
WC_MGF1SHA224: int
WC_MGF1SHA256: int
WC_MGF1SHA384: int
WC_MGF1SHA512: int

WC_HASH_TYPE_NONE: int
WC_HASH_TYPE_MD2: int
WC_HASH_TYPE_MD4: int
WC_HASH_TYPE_MD5: int
WC_HASH_TYPE_SHA: int
WC_HASH_TYPE_SHA224: int
WC_HASH_TYPE_SHA256: int
WC_HASH_TYPE_SHA384: int
WC_HASH_TYPE_SHA512: int
WC_HASH_TYPE_MD5_SHA: int
WC_HASH_TYPE_SHA3_224: int
WC_HASH_TYPE_SHA3_256: int
WC_HASH_TYPE_SHA3_384: int
WC_HASH_TYPE_SHA3_512: int
WC_HASH_TYPE_BLAKE2B: int
WC_HASH_TYPE_BLAKE2S: int

WC_ML_KEM_512: int
WC_ML_KEM_768: int
WC_ML_KEM_1024: int

WC_ML_DSA_44: int
WC_ML_DSA_65: int
WC_ML_DSA_87: int

WC_KEYTYPE_ALL: int

PRIVATEKEY_TYPE: int
PUBLICKEY_TYPE: int
CERT_TYPE: int
MAX_DER_DIGEST_SZ: int
SHAh: int
SHA256h: int
SHA384h: int
SHA512h: int


RNG: TypeAlias = FFI.CData

def wc_SetSeed_Cb(cb: FFI.CData) -> int: ...
def wolfCrypt_SetPrivateKeyReadEnable_fips(enable: int, key_type: int) -> int: ...
def wc_GetErrorString(error: int) -> FFI.CData: ...

def wc_InitRngNonce_ex(rng: RNG, nonce: bytes, nonce_size: int, heap: FFI.CData, device_id: int) -> int: ...
def wc_RNG_GenerateByte(rng: RNG, buffer: FFI.CData) -> int: ...
def wc_RNG_GenerateBlock(rng: RNG, buffer: FFI.CData, len: int) -> int: ...
def wc_FreeRng(rng: RNG) -> None: ...

DerBufferPtr: TypeAlias = FFI.CData
EncryptedInfo: TypeAlias = FFI.CData
IntPtr: TypeAlias = FFI.CData
BytePtr: TypeAlias = FFI.CData

def wc_PemToDer(buff: bytes, buf_size: int, type: int, der: DerBufferPtr, heap: FFI.CData, info: EncryptedInfo,
                key_format: IntPtr) -> int: ...
def wc_DerToPemEx(der: bytes, der_size: int, output: FFI.CData, output_size: int, cipher_info: FFI.CData,
                  type: int) -> int: ...
def wc_FreeDer(der: DerBufferPtr) -> None: ...
def wc_EncodeSignature(out: BytePtr, digest: bytes, digest_size: int, hash_oid: int) -> int: ...

def wc_PBKDF2(out: BytePtr, passwd: bytes, pass_len: int, salt: bytes, salt_len: int, iterations: int, keylen: int,
              hash_type: int) -> int: ...

def wc_InitSha(obj: FFI.CData) -> int: ...
def wc_ShaCopy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_ShaUpdate(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_ShaFinal(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_ShaFree(obj: FFI.CData) -> None: ...

def wc_InitSha256(obj: FFI.CData) -> int: ...
def wc_Sha256Copy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_Sha256Update(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_Sha256Final(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_Sha256Free(obj: FFI.CData) -> None: ...

def wc_InitSha384(obj: FFI.CData) -> int: ...
def wc_Sha384Copy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_Sha384Update(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_Sha384Final(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_Sha384Free(obj: FFI.CData) -> None: ...

def wc_InitSha512(obj: FFI.CData) -> int: ...
def wc_Sha512Copy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_Sha512Update(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_Sha512Final(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_Sha512Free(obj: FFI.CData) -> None: ...

def wc_InitSha3_224(obj: FFI.CData, heap: FFI.CData, dev_id: int) -> int: ...
def wc_Sha3_224_Copy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_Sha3_224_Update(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_Sha3_224_Final(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_Sha3_224_Free(obj: FFI.CData) -> None: ...

def wc_InitSha3_256(obj: FFI.CData, heap: FFI.CData, dev_id: int) -> int: ...
def wc_Sha3_256_Copy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_Sha3_256_Update(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_Sha3_256_Final(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_Sha3_256_Free(obj: FFI.CData) -> None: ...

def wc_InitSha3_384(obj: FFI.CData, heap: FFI.CData, dev_id: int) -> int: ...
def wc_Sha3_384_Copy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_Sha3_384_Update(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_Sha3_384_Final(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_Sha3_384_Free(obj: FFI.CData) -> None: ...

def wc_InitSha3_512(obj: FFI.CData, heap: FFI.CData, dev_id: int) -> int: ...
def wc_Sha3_512_Copy(src: FFI.CData, dst: FFI.CData) -> int: ...
def wc_Sha3_512_Update(obj: FFI.CData, data: bytes, size: int) -> int: ...
def wc_Sha3_512_Final(obj: FFI.CData, ret: FFI.CData) -> int: ...
def wc_Sha3_512_Free(obj: FFI.CData) -> None: ...

def wc_HmacInit(hmac: FFI.CData, heap: FFI.CData, dev_id: int) -> int: ...
def wc_HmacSetKey(hmac: FFI.CData, type: int, key: bytes, length: int) -> int: ...
def wc_HmacUpdate(hmac: FFI.CData, data: bytes, size: int) -> int: ...
def wc_HmacFinal(hmac: FFI.CData, hash: FFI.CData) -> int: ...
def wc_HmacFree(hmac: FFI.CData) -> None: ...

def wc_HKDF(type: int, in_key: bytes, in_key_size: int, salt: bytes, salt_size: int, info: bytes, info_size: int, out: FFI.CData, out_size: int) -> int: ...
def wc_HKDF_Extract(type: int, salt: bytes, salt_size: int, in_key: bytes, in_key_size: int, out: FFI.CData) -> int: ...
def wc_HKDF_Expand(type: int, in_key: bytes, in_key_size: int, info: bytes, info_size: int, out: FFI.CData, out_size: int) -> int: ...
